### ISSUE TITLE
New iconoir release

### ISSUE THREAD

**Issue by DaniFoldi** [iyashpal/iconoir-vue#1]
Hi 👋,

I've been using your project for importing icons into vue projects, and it's been working great. They have just released version 6.0. Are there any plans to update this package, and potentially automate the whole process for future non-breaking releases? I'm happy to give a GitHub Action a go sometime soon if you are happy with PRs.

**Comment by iyashpal** [comment]
Hi @DaniFoldi 

Yes, releasing version 6.0 is planned for tomorrow.

**Comment by iyashpal** [comment]
PRs are welcome, Thank you.
